# -*- coding: utf-8 -*-
"""Legacy pre-QBF SAT prototype.

This file is retained only for historical comparison. It constructs the old
C-only, 11-weight-bucket SAT gadget and is not used by the current C/D TQBF
implementation or visualization.

Original Colab-export text follows.
"""

"""stableVoting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYOePsyNNvNX9yb8uytA9NYspQYxqyE1

# Imports
"""

# !pip install pref_voting

import itertools
import os, re, random
from collections import defaultdict
from typing import Dict, Tuple, Set, List, Optional, Iterable, Union

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

from pref_voting.profiles import *
from pref_voting.voting_methods import *
from pref_voting.generate_profiles import *
from pref_voting.weighted_majority_graphs import MarginGraph

"""#SAT Stuff"""

# --- Parsing helpers ---
# Compiled once, case-insensitive for 'x' or 'X'
_LIT_RE = re.compile(r'(~)?x(\d+)', re.IGNORECASE)
def parse_clause(clause_str: str) -> Tuple[int, Dict[int, str]]:
    """
    Parse a single clause string like "(x1, ~x2, ~x3)" into:
      - n: max variable index observed
      - polarity: dict {i: 'pos'|'neg'} for literals appearing in the clause
    e.g. "(x1, ~x2, ~x3)" -> (3, {1: 'pos', 2: 'neg', 3: 'neg'})

    Notes:
      - Duplicate literals for the same variable within a clause are allowed only
        if they have the same polarity; contradictory duplicates raise ValueError.
    """
    lits = _LIT_RE.findall(clause_str)
    if not lits:
        raise ValueError("No literals found. Expected format like '(x1, ~x2, x5)'.")
    idxs = [int(j) for _, j in lits]
    n = max(idxs)
    #the second version throws if we see two contradicting literals (x, ~x)
    # polarity = {int(j): ('neg' if s == '~' else 'pos') for s, j in lits}
    polarity: Dict[int, str] = {}
    for s, j in lits:
        i = int(j)
        pol = 'neg' if s == '~' else 'pos'
        if i in polarity and polarity[i] != pol:
            raise ValueError(f"Contradictory literals for x{i} in clause: both pos and neg.")
        polarity[i] = pol
    return n, polarity

def parse_clauses(clauses: Union[str, Iterable[str]]) -> Tuple[int, int, List[Dict[int, str]]]:
    """ Parse multiple clauses.
    Accepts:
      - A single string containing multiple parenthesized clauses, e.g.:
          "(x1, ~x2, x3) (x2, x4) ∧ (~x1, x4)"
        (any separators outside parentheses are ignored)
      - OR an iterable of clause strings, e.g.:
          ["(x1, ~x2, x3)", "(x2, x4)", "(~x1, x4)"]

    Returns:
      - n_max: maximum variable index across all clauses
      - num_clauses: number of clauses
      - clauses_polarity: list of per-clause polarity dicts {var_index: 'pos'|'neg'}
    """
    # Normalize input to a list of clause strings
    if isinstance(clauses, str):
        # Extract each (...) group; tolerate any separators between them
        groups = re.findall(r'\(([^)]*)\)', clauses)
        clause_strs = [f'({g})' for g in groups] if groups else [clauses]
    else:
        clause_strs = list(clauses)

    if not clause_strs:
        raise ValueError("No clauses provided.")

    clauses_polarity: List[Dict[int, str]] = []
    n_max = 0

    for c in clause_strs:
        n, pol = parse_clause(c)
        n_max = max(n_max, n)
        clauses_polarity.append(pol)

    num_clauses = len(clauses_polarity)
    return n_max, num_clauses, clauses_polarity

def fibonacci_series(n: int, seed1: int, seed2: int) -> List[int]:
    """
    Generates the fibonacci series of length n starting at two seed values.

    Args:
        n: The number of terms in the series.
        seed1: The first seed value.
        seed2: The second seed value.

    Returns:
        A list containing the fibonacci series.
    """
    if n <= 0:
        return []
    if n == 1:
        return [seed1]
    if n == 2:
        return [seed1, seed2]

    series = [seed1, seed2]
    while len(series) < n:
        next_term = series[-1] + series[-2]
        series.append(next_term)
    return series

# Example usage:
# print(fibonacci_series(10, 0, 1))
# print(fibonacci_series(5, 2, 3))

"""# Tournament/Graph Construction"""

weights = None
curr_group = None
curr_delta = None
NUM_GROUPS = 11
def next_group():
    global curr_delta, curr_group
    if weights is None or curr_group is None or curr_delta is None:# error
        raise ValueError("error: called next_weight without initializing params")
    elif curr_group < 0:
        raise ValueError("error: called next_group too many times")
    curr_group -= 1
    curr_delta = 0
def next_weight():
    global weights, curr_group, curr_delta
    if weights is None or curr_group is None or curr_delta is None:# error
        raise ValueError("error: called next_weight without initializing params")
    curr_delta -= 1
    return weights[curr_group] + curr_delta-1
def small_jump_next_weight():
    for _ in range(10):
        next_weight()

# --- Graph construction from spec (dynamic in n) ---
def build_graph_from_spec(clause_str:str, starting_weight:int = 1000, weight_perm: list[int] | None = None):
    global weights, curr_group, curr_delta, NUM_GROUPS
    # Parse all clauses -> n (max var index), # clauses, and per-clause polarity dicts
    n, m, clause_polarities = parse_clauses(clause_str)  # [(i -> 'pos'|'neg'), ...]
    G = nx.DiGraph()
    C = "C"
    L = [f"L{k}" for k in range(1, m+1)]
    T = [f"T{i}" for i in range(1, n+1)]
    F = [f"F{i}" for i in range(1, n+1)]
    X = [f"X{i}" for i in range(1, n+1)]
    G.add_nodes_from([C] + L + T + F + X)

    #group 1: C -> Fi, Ti
    #group 2: Fi, Ti -> Xi
    #group 3: {Ti, Fj \in clause k} -> Lk
    #group 4: Lk -> {Fi, Tj \notin clause k}
    #group 5: Xj -> {Fi, Ti \forall i!=j}
    #group 6: Xi -> Lk \forall i \forall k (... L to Xi??)
    #group 7: Lk -> C \forall k
    #group 8: Xi -> C (first relevant thing checked in negative is these edges)
    #irrelevant below (hopefully)
    #group 9: {Fi -> Ti,
    #          Fi -> Tj \forall j > i,
    #          Ti -> Fj \forall j > i} \forall i
    #group 10: Fi -> Fj \forall i < j     F->F
    #group 11: Ti -> Tj \forall i < j     T->T
    #group 12: Xi -> Xj \forall i < j     X->X
    #group 13: Li -> Lj \forall i < j     L->L

    num_groups = NUM_GROUPS

    if weight_perm is None:
        # default: Fibonacci weights
        weights = fibonacci_series(num_groups, starting_weight, starting_weight*2)
    else:
        if len(weight_perm) != num_groups:
            raise ValueError(f"weight_perm must have length {num_groups}, got {len(weight_perm)}")
        weights = weight_perm

    curr_group = num_groups-1
    curr_delta = 0


    #1) C -> Fi, Ti
    for i in range(1, n+1):
        G.add_edge(C, f"F{i}", weight=next_weight())
        G.add_edge(C, f"T{i}", weight=next_weight())
    next_group()


    #2)  Fi and Ti to xi
    for i in range(1, n+1):
        G.add_edge(f"F{i}",f"X{i}", weight=next_weight())
        G.add_edge(f"T{i}",f"X{i}", weight=next_weight())
    next_group()


    #3) {Ti, Fj \in clause k} -> Lk
    for k, pol in enumerate(clause_polarities, start=1):
        Lk = L[k - 1]
        for i, sense in pol.items():
            if sense == 'pos':
                G.add_edge(f"T{i}", Lk, weight=next_weight())
            elif sense == 'neg':
                G.add_edge(f"F{i}", Lk, weight=next_weight())
    next_group()


    #4) Lk -> {Fi, Tj \notin clause k}
    for k, pol in enumerate(clause_polarities, start=1):
        Lk = L[k - 1]
        vars_in_clause = set(pol.keys())
        for i in range(1, n + 1):
            if i in vars_in_clause:
                sense = pol[i]
                if sense == 'pos':
                    G.add_edge(Lk, f"F{i}", weight=next_weight())  # opposite of T_i
                elif sense == 'neg':
                    G.add_edge(Lk, f"T{i}", weight=next_weight())  # opposite of F_i
            else:
                # variable i not in clause k: send to both
                G.add_edge(Lk, f"F{i}", weight=next_weight())
                G.add_edge(Lk, f"T{i}", weight=next_weight())
    next_group()

    #5) Xj -> {Fi, Ti \forall i!=j}
    for i in range(1, n+1):
        Xi = f"X{i}"
        for j in range(1, n+1):
            if j != i:
                G.add_edge(Xi, f"F{j}", weight=next_weight())
                G.add_edge(Xi, f"T{j}", weight=next_weight())
    next_group()

    #6) Xi -> Lk \forall i \forall k (... L to Xi??)
    for Xi in X:
        for Lk in L:
          G.add_edge(Xi, Lk, weight=next_weight())
    next_group()

    #7) Lk -> C \forall k
    for Lk in L:
      G.add_edge(Lk, C, weight=next_weight())
    next_group()

    #8) Xi -> C
    for Xi in X:
        G.add_edge(Xi, C, weight=next_weight())
    next_group()


    # THE FOLLOWING THREE GROUPS ARE CONSIDERED THE SAME GROUP: 9, 10, 11
    #group 9: {Fi -> Ti,
    #          Fi -> Tj \forall j > i,
    #          Ti -> Fj \forall j > i} \forall i
    for i in range(1, n+1):
        G.add_edge(f"F{i}", f"T{i}", weight=next_weight())
        for j in range(i+1, n+1):
            G.add_edge(f"F{i}", f"T{j}", weight=next_weight())
        for j in range(i+1, n+1):
            G.add_edge(f"T{i}", f"F{j}", weight=next_weight())
    # next_group()
    # put a 10-weight gap between these groups we consider the "same"
    small_jump_next_weight()

    #10) Fi -> Fj \forall i < j
    for i in range(1, n+1):
        for j in range(i+1, n+1):
                G.add_edge(f"F{i}", f"F{j}", weight=next_weight())
    # next_group()
    # put a 10-weight gap between these groups we consider the "same"
    small_jump_next_weight()

    #11) Ti -> Tj \forall i < j
    for i in range(1, n+1):
        for j in range(i+1, n+1):
                G.add_edge(f"T{i}", f"T{j}", weight=next_weight())
    next_group()
    # END SAME GROUP (9-11)



    #12) Xi -> Xj \forall i < j
    for i in range(1, n+1):
        for j in range(i+1, n+1):
            G.add_edge(f"X{i}", f"X{j}", weight=next_weight())
    next_group()

    #13) Li -> Lj \forall i < j
    for i in range(1, m+1):
        for j in range(i+1, m+1):
            G.add_edge(f"L{i}", f"L{j}", weight=next_weight())
    next_group()

    return G, n, clause_polarities

"""## Tournament/Networkx graph conversion"""
def digraph_to_tournament(G: nx.DiGraph) -> Dict[Tuple[int, int], int]:
    """
    Convert a networkx.DiGraph into a tournament dictionary:
        { (u, v): weight }
    Guarantees exactly one directed edge per unordered pair {u,v}.
    """
    tournament: Dict[Tuple[int, int], int] = {}
    nodes = list(G.nodes())
    for i, u in enumerate(nodes):
        for v in nodes[i+1:]:
            if G.has_edge(u, v) and not G.has_edge(v, u):
                if "weight" not in G[u][v]:
                    raise ValueError(f"Missing weight on edge ({u}, {v})")
                tournament[(u, v)] = int(G[u][v]["weight"])

            elif G.has_edge(v, u) and not G.has_edge(u, v):
                if "weight" not in G[v][u]:
                    raise ValueError(f"Missing weight on edge ({v}, {u})")
                tournament[(v, u)] = int(G[v][u]["weight"])

            elif G.has_edge(u, v) and G.has_edge(v, u):
                raise ValueError(f"digraph_to_tournament:Both edges ({u}, {v}) and ({v}, {u}) exist in the graph.")
            else:
                raise ValueError(f"No edge between {u} and {v}, not a tournament.")
    return tournament

def tournament_to_digraph(tournament: Dict[Tuple[int, int], int]) -> nx.DiGraph:
    """ Convert a tournament dictionary back into a networkx.DiGraph with edge weights. """
    G = nx.DiGraph()
    for (u, v), w in tournament.items():
        G.add_edge(u, v, weight=w)
    return G

def tournament_to_edges(tournament: Dict[Tuple[int, int], int]) -> list[Tuple[str,str,str]]:
    """ Convert a tournament dictionary into a list of edges of the form (u,v,w). """
    edges = []
    for (u, v), w in tournament.items():
        edges.append((u,v,w))
    return edges

# def build_adj_and_edge_weights(tournament, candidates):
def build_adj_and_edge_weights(
    tournament: Dict[Tuple[int, int], int],
    candidates: Set[int],
) -> Tuple[Dict[int, List[int]], Dict[Tuple[int, int], int]]:
    adj_list = {i: [] for i in candidates}
    edge_weights = {}
    for (u, v), weight in tournament.items():
        adj_list[u].append(v)
        edge_weights[(u, v)] = weight
    return adj_list, edge_weights

def get_candidates_from_digraph(G: nx.DiGraph):
    return set(G.nodes())

def get_edge_weights_from_digraph(G: nx.DiGraph):
    return {e:G[e[0]][e[1]]['weight'] for e in G.edges()}
# G = nx.DiGraph()
# G.add_edge(0, 1, weight=3)
# G.add_edge(2, 0, weight=-1)
# G.add_edge(1, 2, weight=2)

# tournament = digraph_to_tournament(G)
# print("Tournament dict:", tournament)

# G2 = tournament_to_digraph(tournament)
# print("Edges in round-trip digraph:", list(G2.edges(data=True)))

"""#Stable Voting calculations"""

# --------------------------
# Stable Voting Functions
# --------------------------

tourn_sv: Dict[Tuple[int, int], int] = {}
cand_sv: Set[int] = set()
sv_memo: Dict[frozenset, Tuple[Optional[int], List[int], List[str], Optional[Tuple[int, int, int]]]] = {}

# def margin(i, j, tournament):
def margin(i: int, j: int) -> int:
    """Return the margin of i->j."""
    if (i, j) in tourn_sv:
        return tourn_sv[(i, j)]
    else:
        return -tourn_sv[(j, i)]

# def exists_chain(start, end, tournament, threshold, candidates, visited=None):
def exists_chain(
    start: int,
    end: int,
    threshold: int,
    visited: Optional[Set[int]] = None,
) -> bool:
    """Check if there is a chain from start to end, each margin >= threshold."""
    if visited is None:
        visited = set()
    if start == end:
        return True
    visited.add(start)
    for cand in cand_sv:
        if cand not in visited:
            if margin(start, cand) >= threshold:
                if exists_chain(cand, end, threshold, visited):
                    return True
    return False

# def b_defeats_a(B, A, tournament, candidates):
def b_defeats_a(B: int, A: int) -> bool:
    """Check if B defeats A in the Stable Voting sense."""
    t = -margin(A, B)
    return not exists_chain(A, B, t, visited=set())


# def stable_voting_winner_order(candidates, tournament):
def stable_voting_winner_order() -> Tuple[Optional[int], List[int], List[str], Optional[Tuple[int, int, int]]]:
    """
    Recursively compute:
      - The Stable Voting winner,
      - The order in which other candidates are removed,
      - A textual summary (list of strings),
      - The decisive edge (A, B, margin) that "produces" the winner.
    Returns (winner, removal_order, summary, decisive_edge).
    """
    # print("Next test: candidates = ", cand_sv)
    key = frozenset(cand_sv)
    if key in sv_memo:
        return sv_memo[key]

    summary = None
    if len(cand_sv) == 1:
        single = next(iter(cand_sv))
        # summary.append(f"Base case: only candidate {single} remains.")
        result = (single, [], summary, None)
        sv_memo[key] = result
        return result

    # Build list of "valid" matches for Stable Voting
    matches = []
    for A in cand_sv:
        for B in cand_sv:
            if A == B:
                continue
            m_val = margin(A, B)
            # A->B is valid if margin >= 0 or (margin < 0 and B does not defeat A)
            if m_val >= 0 or (m_val < 0 and not b_defeats_a(B, A)):
                matches.append((A, B, m_val))
    # Sort by descending margin
    matches.sort(key=lambda x: x[2], reverse=True)

    # Recursively remove B if A->B is valid
    for (A, B, m_val) in matches:
        # new_cand = cand_sv - {B}
        cand_sv.remove(B)
        # summary.append(f"Trying removal of candidate {B} via edge ({A}, {B}) with margin {m_val} in G\\{{{B}}} = {sorted(new_cand)}")
        w, sub_order, sub_summary, sub_decisive = stable_voting_winner_order()
        cand_sv.add(B)
        # summary.extend(sub_summary)
        if w == A:
            removal_order = [B] + sub_order
            decisive_edge = (A, B, m_val)
            # summary.append(f"Edge ({A}, {B}) produced the winner: {A}.\nRemoval order so far: {removal_order}")
            result = (A, removal_order, summary, decisive_edge)
            sv_memo[key] = result
            return result

    result = (None, [], summary, None)
    sv_memo[key] = result
    return result

def stable_voting_winner_order_top(G: nx.DiGraph) -> Tuple[Optional[int], List[int], List[str], Optional[Tuple[int, int, int]]]:
    global tourn_sv, cand_sv, sv_memo
    sv_memo.clear()
    # this isn't necessary but makes me feel better
    tourn_sv.clear()
    cand_sv.clear()


    # actually set up globals
    tourn_sv = digraph_to_tournament(G)
    cand_sv = get_candidates_from_digraph(G)
    return stable_voting_winner_order()
# --------------------------
# Graph helper
# --------------------------
# def induced_subtournament(tournament, subset):
def induced_subtournament(
    tournament: Dict[Tuple[int, int], int],
    subset: Set[int] | List[int],
) -> Dict[Tuple[int, int], int]:
    """
    Return the induced subtournament on 'subset' by filtering edges
    whose endpoints are both in 'subset'.
    """
    subset = set(subset)
    return {e:w for e,w in tournament.items() if e[0] in subset and e[1] in subset}

"""#Visualization

Visualization helpers
"""

def print_useful_info_from_sv(result, clause = None):
    winner, removal_order, summary, decisive_edge = result
    if clause: print("Clause: ", clause)
    print("Winner:", winner)
    print("Removal Order:")
    line_len = 80
    for i in range(0, len(removal_order), line_len):
        print(removal_order[i:i + line_len])

    print("Decisive Edge:", decisive_edge)

"""Athina's circular"""

# def draw_graph(adj_list, edge_weights, winning_edge=None, file_name=None):
def draw_graph(
    G: nx.DiGraph,
    winning_edge: Optional[Tuple[int, int, int]] = None,
    file_name: Optional[str] = None,
) -> None:
    """
    Draw the tournament with a circular layout and preserve aspect ratio.
    If winning_edge is given, highlight it:
      - If margin >= 0, color (A->B) in red
      - If margin < 0, flip to (B->A) in green
    """
    plt.figure(figsize=(6, 6))
    pos = nx.circular_layout(G)
    plt.axis('off')
    ax = plt.gca()
    ax.set_aspect('equal', adjustable='datalim')

    highlight_edge = None
    highlight_color = None
    if winning_edge is not None:
        A, B, m_val = winning_edge
        if m_val >= 0:
            highlight_edge = (A, B)
            highlight_color = 'red'
        else:
            highlight_edge = (B, A)
            highlight_color = 'green'

    edge_colors = []
    for (u, v) in G.edges():
        if highlight_edge is not None and (u, v) == highlight_edge:
            edge_colors.append(highlight_color)
        else:
            edge_colors.append('gray')

    nx.draw_networkx_nodes(G, pos, node_color='lightblue', node_size=600)
    nx.draw_networkx_labels(G, pos, labels={x: str(x) for x in G.nodes()}, font_size=12)
    nx.draw_networkx_edges(G, pos, edge_color=edge_colors, arrows=True)

    # Label each edge with its weight
    edge_weights = get_edge_weights_from_digraph(G)
    e_labels = {(u, v): edge_weights[(u, v)] for (u, v) in G.edges()}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=e_labels, font_color='black')

    if file_name:
        plt.savefig(file_name, bbox_inches='tight')
        plt.close()
    else:
        plt.show()

"""Ethan's fancy drawing"""



"""# Actual main

## SAT Testers
"""

#Main
if __name__ == "__main__" and "--run-legacy-demo" in __import__("sys").argv:
    # Satisfiable
    # clause = "(~x1, ~x2, ~x3), (x1, x2, x3)"
    clause = "(x1, x2),(x1,~x2),(~x1,x2),(~x1,~x2)"
    clauses = ["(x1, x2)", "(x1, ~x2)", "(~x1, x2)", "(~x1, ~x2)"]

    # All combinations of size 2, 3
    clause_sets_2_3 = list(itertools.combinations(clauses, 2)) \
                    + list(itertools.combinations(clauses, 3))


    # NOT Satisfiable
    unsat_clauses = [
        # 1) Classic unsat, all possible 2-sat with 2 variables
        ["(x1, x2)", "(x1, ~x2)", "(~x1, x2)", "(~x1, ~x2)"],
        # 2) Force x1 = x2, x2 = x3, but x1 ≠ x3 (inconsistent)
        ["(x1, ~x2)", "(~x1, x2)", "(x2, ~x3)", "(~x2, x3)", "(x1, x3)", "(~x1, ~x3)"],
        # 3) Force x1 and ¬x1 simultaneously via “pseudo-unit” pairs
        ["(x1, x2)", "(x1, ~x2)", "(~x1, x3)", "(~x1, ~x3)"],
        # 4) Two contradictory 3-step implication cycles
        ["(~x1, x2)", "(~x2, x3)", "(~x3, ~x1)", "(x1, ~x2)", "(x2, ~x3)", "(x3, x1)"]
    ]

    """## Running the clauses"""

    STARTING_WEIGHT = 100

    # all sets of 3 of clauses:
    clause_sets = list(itertools.combinations(clauses, 3))
    all_graph_sets = list(build_graph_from_spec(curr, STARTING_WEIGHT) for curr in clause_sets)
    G, n, polarity = build_graph_from_spec(clause, STARTING_WEIGHT)
    curr_clause = clause
    # curr_test_idx = 2
    # G, n, polarity = all_graph_sets[curr_test_idx]
    # curr_clause = clause_sets[curr_test_idx]

    # cats = classify_edges_from_spec(G, n, polarity)
    # counts = edge_counts_summary(cats)
    tournament = digraph_to_tournament(G)

    print("weights used:")
    trash = list(set(tournament.values()))
    for i in range(0, len(trash), 10):
        print(trash[i:i + 10])

    # draw_graph(G)

    import pprint, time
    curr = time.time()#time
    tournament = digraph_to_tournament(G)
    winner, removal_order, summary, decisive_edge = stable_voting_winner_order_top(G)
    print(f"Duration (sec): {time.time() - curr}")#time

    print_useful_info_from_sv((winner, removal_order, summary, decisive_edge), curr_clause)

    tournament = digraph_to_tournament(G)
    mg = MarginGraph(get_candidates_from_digraph(G), tournament_to_edges(tournament))
    winners, elim_dict = stable_voting_with_explanation(mg, algorithm='basic')
    winner = winners[0]

    print("Winner",winner)
    print("Elimination dictionary",elim_dict)

    # todo: master copy below does not match our order printed in this cell
    # Elimination dictionary {'C': ['F1', 'X2', 'X1', 'T1', 'L3', 'F2', 'L2', 'L1', 'T2']}

    """### For all 2-sat combinations, check all permutations of edge weight orders"""

    # for each permutation of the sequence, check that
    # 1) all SAT have C winners
    # 2) all UNSAT have not C winners

    # num_groups = NUM_GROUPS #because we say so, see code above
    weights_perm = fibonacci_series(NUM_GROUPS, STARTING_WEIGHT, STARTING_WEIGHT*2)


    # Optional: SAMPLE instead of iterating all 13! permutations (uncomment to use)
    # perms_iter = (random.sample(weights_perm, k=len(weights_perm)) for _ in range(1000))
    # Otherwise, ALL permutations (warning: 13! is astronomically large):
    # perms_iter = itertools.permutations(weights_perm)
    PRINT_EVERY = 5000
    TIME_EVERY_SEC = 60
    total_time = 0.0
    num_done = 0
    last_report_t = time.time()
    # all_failures = []
    num_all_failures = 0
    num_perms_failed = 0
    all_diffs = []

    total_our_time = 0
    total_their_time = 0
    total_graph_build_time = 0
    total_post_overhead_time = 0
    total_clauses_running = len(clause_sets_2_3) + len(unsat_clauses)

    p_i = -1
    for perm in itertools.permutations(weights_perm):#winner should be C
        p_i += 1
        perm_start = time.time()
        correct = True
        # failures = []
        num_failures = 0
        diff = []
        diff_flag = True

        our_time = 0
        their_time = 0
        graph_build_time = 0
        post_overhead_time = 0

        # --- SAT cases: must produce C as winner ---
        # Get winners for satisfiable cases
        for curr_clause in clause_sets_2_3:
            trash_time = time.time()
            #G, n, polarity
            G, _, _ = build_graph_from_spec(curr_clause, weight_perm=list(perm))
            graph_build_time += time.time() - trash_time


            # trash_time = time.time()
            # # Alg we wrote
            # my_winner, removal_order, summary, decisive_edge = stable_voting_winner_order_top(G)
            # our_time += time.time() - trash_time


            trash_time = time.time()
            # Alg from SV Paper
            tournament = digraph_to_tournament(G)
            mg = MarginGraph(get_candidates_from_digraph(G), tournament_to_edges(tournament))
            winners, elim_dict = stable_voting_with_explanation(mg, algorithm='basic')
            winner = winners[0]
            their_time += time.time() - trash_time


            # trash_time = time.time()
            # if my_winner != winner or removal_order != elim_dict[winner]:
            #   diff_flag = False
            #   diff.append(("Difference in algos:",curr_clause, my_winner, winner))

            if winner != "C":
                correct = False
                # failures.append(("SAT_expected_C", curr_clause, winner))
                num_failures += 1
                # Optional: print detailed trace for debugging:
                # print_useful_info_from_sv((winner, removal_order, summary, decisive_edge), curr_clause)
                # print()
                # print(clause)
                # print("Winner",winner)
                # print("Elimination dictionary",elim_dict)
            post_overhead_time += time.time() - trash_time

        # --- UNSAT cases: must NOT produce C as winner ---
        for curr_clause in unsat_clauses:
            trash_time = time.time()
            #G, n, polarity
            G, _, _ = build_graph_from_spec(curr_clause, weight_perm=list(perm))
            graph_build_time += time.time() - trash_time


            # trash_time = time.time()
            # # Alg we wrote
            # my_winner, removal_order, summary, decisive_edge = stable_voting_winner_order_top(G)
            # our_time += time.time() - trash_time


            trash_time = time.time()
            # Alg from SV Paper
            tournament = digraph_to_tournament(G)
            mg = MarginGraph(get_candidates_from_digraph(G), tournament_to_edges(tournament))
            winners, elim_dict = stable_voting_with_explanation(mg, algorithm='basic')
            # https://pref-voting.readthedocs.io/en/latest/margin_based_methods.html#stable-voting
            # https://pref-voting.readthedocs.io/en/latest/_modules/pref_voting/margin_based_methods.html#stable_voting
            # s...with_explanation(edata, curr_cands=None, strength_function=None, algorithm='basic')
            # _s...with_explanation(edata,
            #                       curr_cands = curr_cands,
            #                       strength_function = strength_function,
            #                       terminate_early=False)
            # ws, mem_sv_winners, elim_dict, mem_elim_dict =
            # _stable_voting_with_explanation(edata,
            #                                curr_cands = edata.candidates,
            #                                strength_function = edata.margin,
            #                                sorted_matches = [(a, b, m)...],
            #                                mem_sv_winners = {},
            #                                mem_elim_dict = {},
            #                                terminate_early = terminate_early
            #                                )
            winner = winners[0]
            their_time += time.time() - trash_time


            trash_time = time.time()
            # if my_winner != winner or removal_order != elim_dict[winner]:
            #   diff_flag = False
            #   diff.append(("Difference in algos:",curr_clause, my_winner, winner))

            if winner == "C":
                correct = False
                # failures.append(("UNSAT_expected_not_C", curr_clause, winner))
                num_failures += 1
                # Optional: print detailed trace for debugging:
                # print_useful_info_from_sv((winner, removal_order, summary, decisive_edge), curr_clause)
                # print()
                # print(clause)
                # print("Winner",winner)
                # print("Elimination dictionary",elim_dict)
            post_overhead_time += time.time() - trash_time


        # --- update stats ---
        perm_elapsed = time.time() - perm_start
        total_time += perm_elapsed
        total_our_time += our_time/total_clauses_running
        total_their_time += their_time/total_clauses_running
        total_graph_build_time += graph_build_time/total_clauses_running
        total_post_overhead_time += post_overhead_time/total_clauses_running
        num_done += 1
        if not correct:
            num_all_failures += num_failures
            num_perms_failed += 1
            # for tag, clause, win in failures:
            #     all_failures.append((p_i, tag, clause, win))
        else:
            print("FOUND ONE: ", perm)

        if not diff_flag:
            for tag, clause, my_win, win in diff:
                all_diffs.append((p_i, tag, clause, my_win, win))

        # --- periodic progress report (avg runtime + fail count so far) ---
        now = time.time()
        if (p_i % PRINT_EVERY == 0) or (now - last_report_t >= TIME_EVERY_SEC):
            avg = total_time / num_done
            avg_per_perm = total_time / (num_done * total_clauses_running)
            avg_our_time = total_our_time / num_done
            avg_their_time = total_their_time / num_done
            avg_graph_build_time = total_graph_build_time / num_done
            avg_post_overhead_time = total_post_overhead_time / num_done
            # print(f"[PROGRESS] perms_done={num_done}  avg_time={avg:.4f}s  fails_so_far={len(all_failures)} diffs_so_far={len(all_diffs)}")
            print(f"[PROGRESS] perms_done={num_done}  diffs_so_far={len(all_diffs)}  "\
                  f"fails_so_far={num_all_failures}  perms_failed_so_far={num_perms_failed}  " \
                  f"(avg_perm={avg:.4f}s, avg_case={avg_per_perm:.4f}s avg_our_time={avg_our_time:.4f}s, avg_their_time={avg_their_time:.4f}s, "\
                  f"avg_graph_build_time={avg_graph_build_time:.4f}s, avg_post_overhead_time={avg_post_overhead_time:.4f}s)")
            last_report_t = now

    """### All subgraph tournaments saved"""

    print("Subgraphs of size 3 from sv_memo:")
    for candidate_set, result in sv_memo.items():
        if len(candidate_set) == 4:
            # other conditions:
            if all(x in candidate_set for x in ['C', 'X2', 'L1', 'T2']):
              print(candidate_set)
              print_useful_info_from_sv(result)
              print()

    """### Stable voting library"""

    for clause, (G, _, _) in zip(clause_sets, all_graph_sets):
        tournament = digraph_to_tournament(G)

        mg = MarginGraph(get_candidates_from_digraph(G), tournament_to_edges(tournament))
        winners, elim_dict = stable_voting_with_explanation(mg, algorithm='basic')

        print(clause)
        print("Winner",winners)
        print("Elimination dictionary",elim_dict)
        print()

    # subcandidates = ["C","F1","F2","T3","L"]
    # subtournament = induced_subtournament(tournament, subcandidates)
    # draw_graph(*build_adj_and_edge_weights(subtournament, subcandidates))
    # sub_winner, sub_summary, sub_removal_order, sub_decisive_edge = stable_voting_winner_order_top(G)
    # print("Subtournament winner:", sub_winner)
    # print("Subtournament removal order:", sub_removal_order[-1])
    # print("Subtournament decisive edge:", sub_decisive_edge)

    """## Ethan's goal (code merge)"""

    # G, n, polarity = build_graph_from_spec(clause)
    # cats = classify_edges_from_spec(G, n, polarity)
    # counts = edge_counts_summary(cats)
